### ISSUE TITLE
Render failed after commit 91a5b6

### ISSUE THREAD

**Issue by CHN-beta** [kaiiiz/hexo-theme-book#24]
I noticed the following error while building the init site with v3.0.0:

```
$ hexo clean    
INFO  Validating config
INFO  Deleted database.
INFO  Deleted public folder.
$ hexo generate
INFO  Validating config
INFO  Start processing
FATAL {
  err: TypeError: Cannot read property 'path' of undefined
      at Hexo.<anonymous> (/home/chn/Desktop/hexo/themes/book/scripts/render.js:52:31)
      at Hexo.tryCatcher (/home/chn/Desktop/hexo/node_modules/bluebird/js/release/util.js:16:23)
      at Hexo.<anonymous> (/home/chn/Desktop/hexo/node_modules/bluebird/js/release/method.js:15:34)
      at /home/chn/Desktop/hexo/node_modules/hexo/lib/extend/filter.js:67:52
      at tryCatcher (/home/chn/Desktop/hexo/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/home/chn/Desktop/hexo/node_modules/bluebird/js/release/reduce.js:166:18)
      at Object.gotAccum (/home/chn/Desktop/hexo/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/home/chn/Desktop/hexo/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/chn/Desktop/hexo/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/chn/Desktop/hexo/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/home/chn/Desktop/hexo/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/home/chn/Desktop/hexo/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/home/chn/Desktop/hexo/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/chn/Desktop/hexo/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/chn/Desktop/hexo/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
```

But v2.1.0 works well.

I tried to figure out why. I found that after removing the following code in `scripts/render.js` at line 51, v3.0.0 works.

```
hexo.extend.filter.register('after_generate', function () {
  hexo.route.remove(home_file.path);
  hexo.route.remove(menu_file.path);
});
```

**Comment by kaiiiz** [comment]
The error seems that hexo doesn't find the proper page based on your theme's setting. Have you already change your home.md and menu.md file under `source` folder instead of `source/_posts` folder? This change was made in v3.0.0. (see [changelog](https://kaiiiz.github.io/hexo-theme-book-demo/changelog/)) for more details)

**Comment by CHN-beta** [comment]
> The error seems that hexo doesn't find the proper page based on your theme's setting. Have you already change your home.md and menu.md file under `source` folder instead of `source/_posts` folder? This change was made in v3.0.0. (see [changelog](https://kaiiiz.github.io/hexo-theme-book-demo/changelog/) for more details)

Yes, it is my wrong.
