### ISSUE TITLE
error when hexo g

### ISSUE THREAD

**Issue by forliuyifei** [kaiiiz/hexo-theme-book#27]
```
FATAL {
  err: TypeError: Cannot read property 'path' of undefined
      at Hexo.<anonymous> (/data/data/com.termux/files/home/py.loafing.cn/themes/book/scripts/render.js:52:31)
      at Hexo.tryCatcher (/data/data/com.termux/files/home/py.loafing.cn/node_modules/bluebird/js/release/util.js:16:23)
      at Hexo.<anonymous> (/data/data/com.termux/files/home/py.loafing.cn/node_modules/bluebird/js/release/method.js:15:34)
      at /data/data/com.termux/files/home/py.loafing.cn/node_modules/hexo/lib/extend/filter.js:67:52
      at tryCatcher (/data/data/com.termux/files/home/py.loafing.cn/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/data/data/com.termux/files/home/py.loafing.cn/node_modules/bluebird/js/release/reduce.js:166:18)
      at Object.gotAccum (/data/data/com.termux/files/home/py.loafing.cn/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/data/data/com.termux/files/home/py.loafing.cn/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/data/data/com.termux/files/home/py.loafing.cn/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/data/data/com.termux/files/home/py.loafing.cn/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/data/data/com.termux/files/home/py.loafing.cn/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/data/data/com.termux/files/home/py.loafing.cn/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/data/data/com.termux/files/home/py.loafing.cn/node_modules/bluebird/js/release/async.js:86:9)              at Async._drainQueues (/data/data/com.termux/files/home/py.loafing.cn/node_modules/bluebird/js/release/async.js:102:5)      at Immediate.Async.drainQueues [as _onImmediate] (/data/data/com.termux/files/home/py.loafing.cn/node_modules/bluebird/js/release/async.js:15:14)                                         at processImmediate (internal/timers.js:456:21)         } Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
```

**Comment by kaiiiz** [comment]
I think this is an issue which has been mentioned in issue #24. Please check your `home.md` and `menu.md` file path are matched with the config file, since v3.0.0 has change the directory path from `source/_post` to `source`.

**Comment by forliuyifei** [comment]
> I think this is an issue which has been mentioned in issue #24. From v3.0.0, home and menu file's directory are changed from `source/_post` to `source`, for more details, see [changelog](https://kaiiiz.github.io/hexo-theme-book-demo/changelog/).

Thanks!
