### ISSUE TITLE
  err: TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by superyyf** [kaiiiz/hexo-theme-book#30]
when i change theme to book then run hexo g command

yyf@yyf-GP62-2QE:~/superyyf.github.io$ hexo g
INFO  Validating config
INFO  Start processing
FATAL {
  err: TypeError: Cannot read property 'path' of undefined
      at Hexo.<anonymous> (/home/yyf/superyyf.github.io/themes/book/scripts/render.js:52:31)
      at Hexo.tryCatcher (/home/yyf/superyyf.github.io/node_modules/bluebird/js/release/util.js:16:23)
      at Hexo.<anonymous> (/home/yyf/superyyf.github.io/node_modules/bluebird/js/release/method.js:15:34)
      at /home/yyf/superyyf.github.io/node_modules/hexo/lib/extend/filter.js:67:52
      at tryCatcher (/home/yyf/superyyf.github.io/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/home/yyf/superyyf.github.io/node_modules/bluebird/js/release/reduce.js:166:18)
      at Object.gotAccum (/home/yyf/superyyf.github.io/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/home/yyf/superyyf.github.io/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/yyf/superyyf.github.io/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/yyf/superyyf.github.io/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/home/yyf/superyyf.github.io/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/home/yyf/superyyf.github.io/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/home/yyf/superyyf.github.io/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/yyf/superyyf.github.io/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/yyf/superyyf.github.io/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html

**Comment by kaiiiz** [comment]
Your `home_file` variable is not initialized, please check your `home_page` and `menu_page` settings in theme's configuration, and make sure these files are correctly put under `/source` folder.

Checkout https://github.com/kaiiiz/hexo-theme-book/wiki/Configuration for more details.
